Team01-Project01/src/Team01-Project01/ViewModels/Account/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Team01_Project01.ViewModels.Account
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

Team01-Project01/src/Team01-Project01/Controllers/FacultiesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Team01_Project01.Models;

namespace Team01Project01.Controllers
{
    public class FacultiesController : Controller
    {
        private AppDbContext _context;

        public FacultiesController(AppDbContext context)
        {
            _context = context;    
        }

        // GET: Faculties
        public IActionResult Index()
        {
            return View(_context.Faculties.ToList());
        }

        // GET: Faculties/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculties.Single(m => m.FacultyId == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Faculties.Add(faculty);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculties.Single(m => m.FacultyId == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Update(faculty);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculties.Single(m => m.FacultyId == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Faculty faculty = _context.Faculties.Single(m => m.FacultyId == id);
            _context.Faculties.Remove(faculty);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Team01-Project01/src/Team01-Project01/Controllers/HomeController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Team01_Project01.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginIndex()
        {
            return View();
        }
        public IActionResult schedulee()
        {
            return View();
        }

        public IActionResult LoginAbout()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Signup()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }


    }
}

Team01-Project01/src/Team01-Project01/Views/Home/About.cshtml
@{
    ViewBag.Title = "Contact";
}


<html>
<head>

    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/Team01.css")" rel="stylesheet">
    <!--  <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    -->
    
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    
    <!--[if lt IE 9]> <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script> <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
  
    <script type="text/javascript" src="~/js/jquery.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/smoothscroll.js"></script>
    <script type="text/javascript" src="~/js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="~/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="~/js/jquery.parallax.js"></script>
    <script type="text/javascript" src="~/js/main.js"></script>
    =======
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/smoothscroll.js"></script>
    <script type="text/javascript" src="js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="js/jquery.parallax.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
   
</head>
<body>

    <div class="preloader">
        <div class="preloder-wrap">
            <div class="preloder-inner">
                <div class="ball"></div>
                <div class="ball"></div>
                <div class="ball"></div>
                <div class="ball"></div>
                <div class="ball"></div>
                <div class="ball"></div>
                <div class="ball"></div>
            </div>
        </div>
    </div><!--/.preloader-->
    <header id="navigation">
        <div class="navbar navbar-inverse navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <img src="~/images/1194394458-scheduler.png" />
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                    </button>
                    @*<a class="navbar-brand" href="index.html"><h1><img src="images/logo.png" alt="logo"></h1></a>*@
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="scroll"><a asp-controller="Home" asp-action="Index" s>Home</a></li>
                        <li class="scroll active"><a asp-controller="Home" asp-action="About">About Us</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Index">Services</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Index">Our Team</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Index">Blog</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <!--  <li><a href="#my-div"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
                        <li><a asp-controller="Home" asp-action="Signup"><span class="glyphicon glyphicon-log-in"></span> Signup</a></li>
                        <li><a asp-controller="Home" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    </ul>
                </div>
            </div>
        </div><!--/navbar-->
    </header> <!--/#navigation-->
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-8 col-sm-offset-2">
                <h2 class="title-one">
                    Meet The Team
                </h2>
                <p>
                    Traditionally, to register the courses students create three or more plans for it. Sometimes there might be only 2 or 3 possible plans available to choose from.
                    Our application aims to aid the students and make it simpler to choose from all the available timings, by creating possible plans.
                    The student just needs to enter the days and timings of your classes and the name of the professors they are interested in and their priorities.
                    The plan with no clashes will be made available to the student. We also try to depict the available schedules in various forms to make it easy for the students to understand and use the resources according to their convenience.
                </p>
            </div>
        </div>
        <div id="team-carousel" class="carousel slide" data-interval="false">
            <a class="member-left" href="#team-carousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
            <a class="member-right" href="#team-carousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
            <div class="carousel-inner team-members">
                <div class="row item active">
                    <div class="col-sm-6 col-md-3">
                        <div class="single-member">
                            <img src="~/images/naresh.jpg" alt="team member" />
                            <br />
                            <h4>Manindra Naresh Kumar</h4>
                            <h5>Controller &amp; routing lead</h5>
                            <div class="socials">
                                <a href="https://www.facebook.com/manindra.naresh"><i> <img src="~/images/opened4.png" border="0"></i></a>
                                <a href="mailto:s525248@mail.nwmissouri.edu"><i><img src="http://s29.postimg.org/3vev14vab/Facebook_48.png" border="0"></i></a>
                                <a href="https://www.linkedin.com/in/manindra-naresh-9683086b"><i><img src="http://s29.postimg.org/95jtsffj7/Linked_In_48.png" border="0"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="single-member">
                            <img src="~/images/anvesh.jpg" alt="team member" />
                            <h4> Anveshkumar Kolluri</h4>
                            <h5>Issues Lead &amp; Repo Admin</h5>
                            <div class="socials">
                                <a href="https://www.facebook.com/anveshkolluri93"><i> <img src="~/images/opened4.png" border="0"></i></a>
                                <a href="mailto:s525272@mail.nwmissouri.edu"><i><img src="http://s29.postimg.org/3vev14vab/Facebook_48.png" border="0"></i></a>
                                <a href="https://www.linkedin.com/in/anvesh-kolluri-7b0a347a?trk=hp-identity-name"><i><img src="http://s29.postimg.org/95jtsffj7/Linked_In_48.png" border="0"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="single-member">
                            <img src="~/images/raihan.jpg" alt="team member" />
                            <h4> Raihan Ahmed</h4>
                            <h5>Project Planning, Reporting &amp; Presentation Lead</h5>
                            <div class="socials">
                                <a href="https://www.facebook.com/raihan.ahmed.9083"><i> <img src="~/images/opened4.png" border="0"></i></a>
                                <a href="mailto:s525248@mail.nwmissouri.edu"><i><img src="http://s29.postimg.org/3vev14vab/Facebook_48.png" border="0"></i></a>
                                <a href="https://www.linkedin.com/in/mraihanahmed"><i><img src="http://s29.postimg.org/95jtsffj7/Linked_In_48.png" border="0"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="single-member">
                            <img src="~/images/chandu.jpg" alt="team member" />
                            <h4>Chandrakanth Podishetty</h4>
                            <h5>Views, views model & Testing Lead</h5>
                            <div class="socials">
                                <a href="https://www.facebook.com/chandu.podisetty"><i> <img src="~/images/opened4.png" border="0"></i></a>
                                <a href="mailto:s522612@mail.nwmissouri.edu"><i><img src="http://s29.postimg.org/3vev14vab/Facebook_48.png" border="0"></i></a>
                                <a href="https://www.linkedin.com/in/chandrakanth-podishetty/"><i><img src="http://s29.postimg.org/95jtsffj7/Linked_In_48.png" border="0"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row item">
                    <div class="col-sm-6 col-md-3">
                        <div class="single-member">
                            <img src="~/images/jagad.jpg" alt="team member" />
                            <h4>Jagadeesh Babu Basimsetty</h4>
                            <h5>Models,Persistence Lead & Testing Lead</h5>
                            <div class="socials">
                                <a href="https://www.facebook.com/jb.jagadeesh"><i> <img src="~/images/opened4.png" border="0"></i></a>
                                <a href="mailto:s522563@mail.nwmissouri.edu"><i><img src="http://s29.postimg.org/3vev14vab/Facebook_48.png" border="0"></i></a>
                                <a href="https://www.linkedin.com/in/JagadeeshBasimsetty"><i><img src="http://s29.postimg.org/95jtsffj7/Linked_In_48.png" border="0"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="single-member">
                            <img src="~/images/sai.jpg" alt="team member" />
                            <h4>Sigh Krihsh-nah(iswar)</h4>
                            <h5>Presentation Lead &amp; Documentation Lead </h5>
                            <div class="socials">
                                <a href="https://www.facebook.com/Saikrishna.ch"><i> <img src="~/images/opened4.png" border="0"></i></a>
                                <a href="mailto:s522570@mail.nwmissouri.edu"><i><img src="http://s29.postimg.org/3vev14vab/Facebook_48.png" border="0"></i></a>
                                <a href="https://www.linkedin.com"><i><img src="http://s29.postimg.org/95jtsffj7/Linked_In_48.png" border="0"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html> 

Team01-Project01/src/Team01-Project01/Views/Home/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<html>
<head>

    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/Team01.css")" rel="stylesheet">

    <!--  <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]> <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script> <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">

    <script type="text/javascript" src="~/js/jquery.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/smoothscroll.js"></script>

    <script type="text/javascript" src="~/js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="~/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="~/js/jquery.parallax.js"></script>
    <script type="text/javascript" src="~/js/main.js"></script>
    <script>
        function validate() {
            var username = document.getElementById("username").value;
            var password = document.getElementById("password").value;
            if (myform.username.value.length == 0) {
                document.getElementById("usernameError").innerHTML = "You must enter a username";

                return false;
            }
            if (myform.password.value.length == 0) {
                document.getElementById("passwordError").innerHTML = "You must enter a password";
                return false;
            }
            if (username == "s525272" && password == "s525272") {
                window.location="LoginIndex"

                /*opens the target page while Id & password matches*/
            } else {
                if (username == "admin" && password == "admin") {
                    window.location="AdminHome"/*opens the target page while Id & password matches*/
                }


                else {
                    alert("Error Password or Username")/*displays error message*/
                }
                ;

            }
        }
    </script>
</head>
<body>
    <header id="navigation">
        <div class="navbar navbar-inverse navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
                    </button>
                    @*<a class="navbar-brand" href="index.html"><h1><img src="images/logo.png" alt="logo"></h1></a>*@
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="scroll"><a asp-controller="Home" asp-action="Index">HOME</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="About">ABOUT US</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Index">SERVICES</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Index">OUR TEM</a></li>

                        <li class="scroll"><a asp-controller="Home" asp-action="Index">BLOG</a></li>
                        <li class="scroll"><a asp-controller="Home" asp-action="Contact">CONTACT</a></li>
                        <!--  <li><a href="#my-div"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
                        <li><a asp-controller="Home" asp-action="Signup"><span class="glyphicon glyphicon-log-in"></span> SIGN UP</a></li>

                        <li><a asp-controller="Home" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> LOGIN</a></li>
                    </ul>
                </div>
            </div>
        </div><!--/navbar-->
    </header> <!--/#navigation-->
    <div class="container">


        <div class="row vertical-offset-100">
            <div style="float:left"></div>
            <div class="col-md-5 col-md-offset-4">



                <div class="panel panel-default" style="float: right">


                    <div class="panel-heading">
                        <div class="panel-title"><b>Sign In</b></div>
                        <div style="float:right; font-size: 80%; position: relative; color:Blue; top:-10px">
                            <a data-target="#myModal" href="#" data-toggle="modal">Forgot password?</a>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Forgot Password?</h4>
                                </div>
                                <fieldset>
                                    <div class="form-group col-sm-10">
                                        <input class="form-control input" placeholder="E-mail Address" name="email" type="email">
                                    </div>

                                </fieldset>
                                <input class="btn btn btn-primary col-sm-4 " style="float:right" value="Send" type="submit" data-dismiss="modal"><br />
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="panel-body">
                        <form class="login" id="myform">
                            <div id="usernameError"></div>

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user col-xs-5"></i></span>
                                <input id="username" type="text" required="required" class="form-control col-xs-5" name="username" value="" placeholder="username or email">

                            </div>

                            <div id="passwordError"></div>

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock col-xs-5"></i></span>
                                <input id="password" type="password" required="required" class="form-control col-xs-5" name="password" placeholder="password">
                            </div>
                            <div class="input-group">
                                <div class="checkbox">
                                    <label>
                                        <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                                    </label>
                                </div>
                            </div>

                            <div style="margin-top:10px" class="form-group">
                                <!-- Button -->

                                <div class="col-sm-12 controls form-group">
                                    <input type="button" class="btn btn-success" value="Login" id="submit" onclick="validate();" />
                                    <a asp-controller="Faculties" asp-action="Index">..</a>


                                </div>
                            </div>
                            <!-- <input type="button" id="signin" name="submit" value="Sign In" class="btn btn-success btn-sm" onclick="verifyLogin()"/>-->

                            <div>
                                <p id="error" style="color: red"></p>
                            </div>
                        </form>
                    </div>
                    <div>


                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>